networks:
  bridge: {}

services:
  app:
    container_name: edge_auctions_app
    build: .
    restart: always
    volumes:
      - ./logs:/logs
      - ./images:/images
    depends_on:
      - db
    networks:
      - bridge
  db:
    container_name: edge_auctions_db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: edge_auctions_db
      PGDATA: /db
    ports:
      - 5432:5432
    volumes:
      - ./db:/db
    networks:
      - bridge
  client:
    container_name: edge_auctions_client
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./sockets/:/sockets
      - ./images:/static/dist/images
    depends_on:
      - app
    networks:
      - bridge
    ports:
      - 80:80
      - 443:443
