networks:
  bridge: {}

services:
  app:
    build: .
    volumes:
      - ./logs:/logs
    depends_on:
      - db
    networks:
      - bridge
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /db
    ports:
      - 5432:5432
    volumes:
      - ./db:/db
    networks:
      - bridge
  client:
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./sockets/:/sockets
    depends_on:
      - app
    networks:
      - bridge
    ports:
      - 80:80
      - 443:443
