"""Changing upca field length and adding missing columns

Revision ID: 03975a66883e
Revises: 8854f9fef21f
Create Date: 2022-08-26 04:40:41.208494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03975a66883e'
down_revision = '8854f9fef21f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids_external_entities')
    op.add_column('external_entities', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('external_tokens', sa.Column('request_history', sa.ARRAY(sa.DateTime(timezone=True)), nullable=True))
    op.alter_column('items', 'upca', type_=sa.String(13))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_tokens', 'request_history')
    op.drop_column('external_entities', 'extra')
    op.create_table('bids_external_entities',
    sa.Column('bid_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], name='bids_external_entities_bid_id_fkey'),
    sa.ForeignKeyConstraint(['entity_id'], ['external_entities.id'], name='bids_external_entities_entity_id_fkey')
    )
    # ### end Alembic commands ###
