"""Adding last prompt date to user

Revision ID: 0d1278b77dcc
Revises: 58be072a1fce
Create Date: 2023-03-03 00:25:31.271958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1278b77dcc'
down_revision = '58be072a1fce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_prompted_for_address_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_prompted_for_address_at')
    # ### end Alembic commands ###
