"""Adding phone to user

Revision ID: 213be3ea14d4
Revises: 8a8b33ba107c
Create Date: 2023-03-02 23:17:34.453533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213be3ea14d4'
down_revision = '8a8b33ba107c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=255), nullable=True))
    # op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
