"""Adding invoice id to auction

Revision ID: 292b5e48fc26
Revises: 19b843b6344d
Create Date: 2023-03-05 00:36:43.312131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292b5e48fc26'
down_revision = '19b843b6344d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('invoice_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'invoice_id')
    # ### end Alembic commands ###
