"""Initial migration

Revision ID: 2e99669e439c
Revises: 
Create Date: 2023-01-28 15:59:39.513887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e99669e439c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anti_sniper', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('usd', sa.Float(), nullable=True),
    sa.Column('rub', sa.Integer(), nullable=True),
    sa.Column('buy_now_price', sa.Integer(), nullable=True),
    sa.Column('buy_now_expires', sa.Integer(), nullable=True),
    sa.Column('bid_start_price', sa.Integer(), nullable=True),
    sa.Column('bid_min_step', sa.Integer(), nullable=True),
    sa.Column('bid_multiple_of', sa.Integer(), nullable=True),
    sa.Column('manual', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='f', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_category_id', sa.Integer(), nullable=True),
    sa.Column('wrap_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['price_category_id'], ['price_categories.id'], ),
    sa.ForeignKeyConstraint(['wrap_to_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supply_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('uploaded_items', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('wrap_to_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('upca', sa.String(length=12), nullable=True),
    sa.Column('upc5', sa.String(length=5), nullable=True),
    sa.Column('price_category_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='supplyitemparsestatus'), nullable=True),
    sa.Column('parse_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['price_category_id'], ['price_categories.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['supply_sessions.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['item_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wrap_to_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('date_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buy_now_price', sa.Integer(), nullable=True),
    sa.Column('buy_now_expires', sa.Integer(), nullable=True),
    sa.Column('bid_start_price', sa.Integer(), nullable=True),
    sa.Column('bid_min_step', sa.Integer(), nullable=True),
    sa.Column('bid_multiple_of', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['set_id'], ['auction_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=32), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('urls', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('is_sniped', sa.Boolean(), nullable=True),
    sa.Column('is_buyout', sa.Boolean(), nullable=True),
    sa.Column('next_bid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('images')
    op.drop_table('auctions')
    op.drop_table('items')
    op.drop_table('supply_sessions')
    op.drop_table('item_types')
    op.drop_table('users')
    op.drop_table('templates')
    op.drop_table('shop_info')
    op.drop_table('price_categories')
    op.drop_table('auction_sets')
    # ### end Alembic commands ###
