"""Adding phone to user

Revision ID: 58be072a1fce
Revises: 213be3ea14d4
Create Date: 2023-03-02 23:18:39.024247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58be072a1fce'
down_revision = '213be3ea14d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
