"""Adding created_at to auth_token

Revision ID: 6b2c0bd0ae49
Revises: 9c2a7e970e1a
Create Date: 2022-07-17 23:15:49.356963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2c0bd0ae49'
down_revision = '9c2a7e970e1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_tokens', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_tokens', 'created_at')
    # ### end Alembic commands ###
