"""Adding last_bidder field

Revision ID: 81d5633a3972
Revises: db73510bedbe
Create Date: 2023-02-15 13:27:59.333008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81d5633a3972'
down_revision = 'db73510bedbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('last_bidder_id', sa.String(255), nullable=True))
    op.create_foreign_key(None, 'auctions', 'users', ['last_bidder_id'], ['id'], ondelete='SET NULL')
    op.drop_column('auctions', 'bid_start_price')
    op.drop_column('auctions', 'bid_multiple_of')
    op.drop_column('auctions', 'is_active')
    op.drop_column('auctions', 'buy_now_expires')
    op.drop_column('auctions', 'buy_now_price')
    op.drop_column('auctions', 'started_at')
    op.drop_column('auctions', 'bid_min_step')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('bid_min_step', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('auctions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('auctions', sa.Column('buy_now_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('auctions', sa.Column('buy_now_expires', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('auctions', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('auctions', sa.Column('bid_multiple_of', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('auctions', sa.Column('bid_start_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'auctions', type_='foreignkey')
    op.drop_column('auctions', 'last_bidder_id')
    # ### end Alembic commands ###
