"""Added ended_at to auction set

Revision ID: 8a8b33ba107c
Revises: 8b5f8009f445
Create Date: 2023-03-02 20:41:16.262460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8b33ba107c'
down_revision = '8b5f8009f445'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_sets', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction_sets', 'ended_at')
    # ### end Alembic commands ###
