"""Adding invoice link to auction

Revision ID: 8b5f8009f445
Revises: 18e102299662
Create Date: 2023-02-28 00:00:14.706919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5f8009f445'
down_revision = '18e102299662'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('invoice_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'invoice_link')
    # ### end Alembic commands ###
