"""Replaced image_url and thumb_url with urls json

Revision ID: a8bb65be4484
Revises: c2d262fb7453
Create Date: 2022-07-24 22:51:40.867478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8bb65be4484'
down_revision = 'c2d262fb7453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'images',
        sa.Column(
            'urls',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{}',
            nullable=True),
    )
    op.drop_column('images', 'thumb_url')
    op.drop_column('images', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('thumb_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('images', 'urls')
    # ### end Alembic commands ###
