"""Updating push model

Revision ID: b3222fa023ff
Revises: eb6a727efb9e
Create Date: 2023-02-19 18:28:09.414438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3222fa023ff'
down_revision = 'eb6a727efb9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('endpoint', sa.Text(), unique=True, nullable=False))
    op.drop_column('push_subscriptions', 'subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('push_subscriptions', 'endpoint')
    # ### end Alembic commands ###
