"""Upgrading codebase to modern declarative base

Revision ID: c13963ca0377
Revises: 292b5e48fc26
Create Date: 2023-03-18 18:02:02.647086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c13963ca0377'
down_revision = '292b5e48fc26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auction_sets', 'date_due',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('auction_sets', 'anti_sniper',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('auction_sets', 'ended_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('auction_sets', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('auctions', 'set_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('auctions', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('auctions', 'date_due',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('bids', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bids', 'auction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bids', 'value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bids', 'is_sniped',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bids', 'is_buyout',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('images', 'mime_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('images', 'urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('images', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('items', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('items', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('items', 'parse_status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='supplyitemparsestatus'),
               nullable=False)
    op.alter_column('items', 'parse_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('price_categories', 'alias',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('price_categories', 'usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('price_categories', 'rub',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('price_categories', 'bid_start_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('price_categories', 'bid_min_step',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('price_categories', 'bid_multiple_of',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('price_categories', 'manual')
    op.alter_column('supply_sessions', 'item_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('supply_sessions', 'uploaded_items')
    op.drop_column('supply_sessions', 'total_items')
    op.alter_column('templates', 'alias',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('templates', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('templates', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('templates', 'alias',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('supply_sessions', sa.Column('total_items', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('supply_sessions', sa.Column('uploaded_items', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('supply_sessions', 'item_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('price_categories', sa.Column('manual', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('price_categories', 'bid_multiple_of',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('price_categories', 'bid_min_step',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('price_categories', 'bid_start_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('price_categories', 'rub',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('price_categories', 'usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('price_categories', 'alias',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('items', 'parse_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('items', 'parse_status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='supplyitemparsestatus'),
               nullable=True)
    op.alter_column('items', 'type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('images', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('images', 'urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('images', 'mime_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('bids', 'is_buyout',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bids', 'is_sniped',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bids', 'value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bids', 'auction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bids', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('auctions', 'date_due',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('auctions', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('auctions', 'set_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('auction_sets', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('auction_sets', 'ended_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('auction_sets', 'anti_sniper',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('auction_sets', 'date_due',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
