"""Replacing extension column with mime_type on image

Revision ID: c1c9e85572a7
Revises: cde629592ebc
Create Date: 2022-07-24 03:33:40.336125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c9e85572a7'
down_revision = 'cde629592ebc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('mime_type', sa.String(length=32), nullable=True))
    op.drop_column('images', 'extension')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('extension', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.drop_column('images', 'mime_type')
    # ### end Alembic commands ###
