"""Adding default value to item description

Revision ID: c2d262fb7453
Revises: c1c9e85572a7
Create Date: 2022-07-24 04:34:30.775046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d262fb7453'
down_revision = 'c1c9e85572a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'items',
        'description',
        existing_type=sa.TEXT,
        server_default='{{ name }}',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'items',
        'description',
        existing_type=sa.TEXT,
        server_default='',
    )
    # ### end Alembic commands ###
