"""Adding created_at field to bid

Revision ID: c32373e9d323
Revises: eeada8f70252
Create Date: 2023-02-16 15:58:18.157540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32373e9d323'
down_revision = 'eeada8f70252'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bids', 'created_at')
    # ### end Alembic commands ###
