"""Adding additional constraints to various columns

Revision ID: cde629592ebc
Revises: 6b2c0bd0ae49
Create Date: 2022-07-23 21:23:35.817932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde629592ebc'
down_revision = '6b2c0bd0ae49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'item_types',
        'name',
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.create_unique_constraint('item_types_name_unique', 'item_types', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_types_name_unique', 'item_types', type_='unique')
    op.alter_column(
        'item_types',
        'name',
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###
