"""Added is_admin field to user

Revision ID: d13e20933f54
Revises: 03975a66883e
Create Date: 2022-10-02 18:35:25.797860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d13e20933f54"
down_revision = "03975a66883e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=False, server_default="f"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
