"""Adding external token model

Revision ID: d45c5e0b954a
Revises: a8bb65be4484
Create Date: 2022-07-30 22:54:00.623936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45c5e0b954a'
down_revision = 'a8bb65be4484'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('VK_USER', 'VK_GROUP', 'TELEGRAM_BOT', name='externaltokentype'), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['external_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_tokens')
    # ### end Alembic commands ###
