"""Adding is_published field

Revision ID: db73510bedbe
Revises: e2dac5dfc3f3
Create Date: 2023-02-15 13:21:00.980979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db73510bedbe'
down_revision = 'e2dac5dfc3f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_sets', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.drop_column('auction_sets', 'started_at')
    op.drop_column('auction_sets', 'ended_at')
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('auction_sets', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('auction_sets', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('auction_sets', 'is_published')
    # ### end Alembic commands ###
